### ISSUE TITLE
\ulnone is not supported 

### ISSUE THREAD

**Issue by Hayato-Hess** [NikolayIT/RTF-DOM-Parser#2]
I noticed when parsing a RTF document which was created by wordpad, that \ulnone is not supported by RtfDomParser. 

"\ulnone - Stops all underlining."

To fix this, I think you can simply add the case

`case RTFConsts._noul:
{
bolStartContent = true;
format.Underline = false;
 break;
 }
`
to the switch statement in RTFDomDocument.cs

**Comment by NikolayIT** [comment]
Could you please open a pull request :-)
